"""Mapping

Revision ID: 16d255294938
Revises: 006_logs_rx
Create Date: 2026-04-05 09:44:27.016444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d255294938'
down_revision: Union[str, None] = '006_logs_rx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_store_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_store_mappings_store_id'), 'user_store_mappings', ['store_id'], unique=False)
    op.create_index(op.f('ix_user_store_mappings_user_id'), 'user_store_mappings', ['user_id'], unique=True)
    op.drop_index('ix_batches_expiry_date', table_name='batches')
    op.drop_index('ix_batches_product_id', table_name='batches')
    op.drop_constraint('uq_batches_product_batch_number', 'batches', type_='unique')
    op.drop_constraint('batches_product_id_fkey', 'batches', type_='foreignkey')
    op.create_foreign_key(None, 'batches', 'products', ['product_id'], ['id'])
    op.drop_index('ix_inventory_batch_id', table_name='inventory')
    op.drop_index('ix_inventory_product_id', table_name='inventory')
    op.drop_index('ix_inventory_store_id', table_name='inventory')
    op.drop_constraint('uq_inventory_store_batch', 'inventory', type_='unique')
    op.drop_constraint('inventory_product_id_fkey', 'inventory', type_='foreignkey')
    op.drop_constraint('inventory_store_id_fkey', 'inventory', type_='foreignkey')
    op.drop_constraint('inventory_batch_id_fkey', 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'inventory', 'stores', ['store_id'], ['id'])
    op.create_foreign_key(None, 'inventory', 'batches', ['batch_id'], ['id'])
    op.drop_index('ix_inventory_logs_created_at', table_name='inventory_logs')
    op.drop_index('ix_inventory_logs_inventory_id', table_name='inventory_logs')
    op.drop_index('ix_inventory_logs_performed_by', table_name='inventory_logs')
    op.drop_constraint('inventory_logs_performed_by_fkey', 'inventory_logs', type_='foreignkey')
    op.drop_constraint('inventory_logs_inventory_id_fkey', 'inventory_logs', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_logs', 'inventory', ['inventory_id'], ['id'])
    op.create_foreign_key(None, 'inventory_logs', 'users', ['performed_by'], ['id'])
    op.drop_index('ix_order_items_batch_id', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_index('ix_order_items_product_id', table_name='order_items')
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_batch_id_fkey', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'batches', ['batch_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_store_id', table_name='orders')
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.drop_index('uq_orders_order_number', table_name='orders')
    op.drop_constraint('orders_store_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'stores', ['store_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_index('ix_prescriptions_order_id', table_name='prescriptions')
    op.drop_constraint('prescriptions_uploaded_by_fkey', 'prescriptions', type_='foreignkey')
    op.drop_constraint('prescriptions_order_id_fkey', 'prescriptions', type_='foreignkey')
    op.create_foreign_key(None, 'prescriptions', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'prescriptions', 'users', ['uploaded_by'], ['id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_users_email', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=320),
               existing_nullable=True)
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.create_foreign_key('prescriptions_order_id_fkey', 'prescriptions', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('prescriptions_uploaded_by_fkey', 'prescriptions', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.create_index('ix_prescriptions_order_id', 'prescriptions', ['order_id'], unique=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('orders_store_id_fkey', 'orders', 'stores', ['store_id'], ['id'], ondelete='RESTRICT')
    op.create_index('uq_orders_order_number', 'orders', ['order_number'], unique=True)
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_store_id', 'orders', ['store_id'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('order_items_batch_id_fkey', 'order_items', 'batches', ['batch_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_batch_id', 'order_items', ['batch_id'], unique=False)
    op.drop_constraint(None, 'inventory_logs', type_='foreignkey')
    op.drop_constraint(None, 'inventory_logs', type_='foreignkey')
    op.create_foreign_key('inventory_logs_inventory_id_fkey', 'inventory_logs', 'inventory', ['inventory_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('inventory_logs_performed_by_fkey', 'inventory_logs', 'users', ['performed_by'], ['id'], ondelete='SET NULL')
    op.create_index('ix_inventory_logs_performed_by', 'inventory_logs', ['performed_by'], unique=False)
    op.create_index('ix_inventory_logs_inventory_id', 'inventory_logs', ['inventory_id'], unique=False)
    op.create_index('ix_inventory_logs_created_at', 'inventory_logs', ['created_at'], unique=False)
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key('inventory_batch_id_fkey', 'inventory', 'batches', ['batch_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('inventory_store_id_fkey', 'inventory', 'stores', ['store_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('inventory_product_id_fkey', 'inventory', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint('uq_inventory_store_batch', 'inventory', ['store_id', 'batch_id'])
    op.create_index('ix_inventory_store_id', 'inventory', ['store_id'], unique=False)
    op.create_index('ix_inventory_product_id', 'inventory', ['product_id'], unique=False)
    op.create_index('ix_inventory_batch_id', 'inventory', ['batch_id'], unique=False)
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.create_foreign_key('batches_product_id_fkey', 'batches', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint('uq_batches_product_batch_number', 'batches', ['product_id', 'batch_number'])
    op.create_index('ix_batches_product_id', 'batches', ['product_id'], unique=False)
    op.create_index('ix_batches_expiry_date', 'batches', ['expiry_date'], unique=False)
    op.drop_index(op.f('ix_user_store_mappings_user_id'), table_name='user_store_mappings')
    op.drop_index(op.f('ix_user_store_mappings_store_id'), table_name='user_store_mappings')
    op.drop_table('user_store_mappings')
    # ### end Alembic commands ###
